import { ClothingListing } from '../types/listing';

export const CURATED_SHOWCASE_LISTINGS: ClothingListing[] = [
  {
    id: 'curated-1',
    title: 'Crimson Silk Wrap Midi Dress',
    description: 'Stunning 100% silk midi dress with puff sleeves and tie waist detail. Worn once for an event.',
    category: 'DRESS',
    brand: 'REFORMATION',
    color: 'Red',
    size: 'S',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 78,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-1',
        imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=700&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-1', name: 'Claire Dupont', city: 'New York', state: 'NY' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'curated-2',
    title: 'Vintage 501 Original Straight Jeans',
    description: 'Authentic 90s high-waisted wash straight leg denim with classic button fly.',
    category: 'BOTTOMWEAR',
    brand: "LEVI'S",
    color: 'Medium Blue',
    size: '27',
    condition: 'GOOD',
    estimatedSwapValue: 52,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-2',
        imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=700&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-2', name: 'Maya Lin', city: 'San Francisco', state: 'CA' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'curated-3',
    title: 'Oversized Wool Blend Trench Coat',
    description: 'Double-breasted trench in camel wool blend. Relaxed modern tailoring.',
    category: 'OUTERWEAR',
    brand: 'ARITZIA',
    color: 'Camel',
    size: 'M',
    condition: 'NEW',
    estimatedSwapValue: 120,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-3',
        imageUrl: 'https://images.unsplash.com/photo-1539533018447-63fcce667823?auto=format&fit=crop&w=700&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-3', name: 'Sophia Rossi', city: 'Chicago', state: 'IL' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'curated-4',
    title: 'Quilted Leather Crossbody Bag',
    description: 'Burgundy pebbled leather with antique gold hardware and adjustable strap.',
    category: 'ACCESSORIES',
    brand: 'COACH',
    color: 'Burgundy',
    size: 'One Size',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 145,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-4',
        imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=700&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-4', name: 'Emma Watson', city: 'Los Angeles', state: 'CA' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'curated-5',
    title: 'Retro Dunk Low Streetwear Sneakers',
    description: 'Vintage colorway, lightly worn sole with original box and clean laces.',
    category: 'FOOTWEAR',
    brand: 'NIKE',
    color: 'White/Navy',
    size: '8.5',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 88,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-5',
        imageUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=700&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-5', name: 'Jordan Reed', city: 'Austin', state: 'TX' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'curated-6',
    title: 'Cropped Cable-Knit Wool Sweater',
    description: 'Warm cream knit with ribbed cuffs and round neck. Perfect layer for autumn.',
    category: 'TOPWEAR',
    brand: 'ZARA',
    color: 'Cream',
    size: 'S',
    condition: 'GOOD',
    estimatedSwapValue: 36,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-6',
        imageUrl: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=700&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-6', name: 'Elena Gomez', city: 'Miami', state: 'FL' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'curated-7',
    title: 'Align High-Rise Yoga Leggings 25"',
    description: 'Buttery-soft Nulu fabric in graphite grey. Flattering fit and seamless waistband.',
    category: 'BOTTOMWEAR',
    brand: 'LULULEMON',
    color: 'Graphite',
    size: '6',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 48,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-7',
        imageUrl: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=700&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-7', name: 'Chloe Bennett', city: 'Seattle', state: 'WA' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'curated-8',
    title: 'Embroidered Floral Boho Maxi Dress',
    description: 'Flowy tiers with vintage-inspired floral embroidery and delicate tassel ties.',
    category: 'DRESS',
    brand: 'FREE PEOPLE',
    color: 'Ivory/Floral',
    size: 'M',
    condition: 'NEW',
    estimatedSwapValue: 95,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-8',
        imageUrl: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=700&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-8', name: 'Harper Ross', city: 'Portland', state: 'OR' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
];
