import { ClothingListing } from '../types/listing';

export const CURATED_SHOWCASE_LISTINGS: ClothingListing[] = [
  // ── 1. Women ─────────────────────────────────────────────────────────────
  {
    id: 'women-1',
    title: "Women's Crimson Silk Wrap Midi Dress",
    description: "Stunning women's 100% silk midi dress with puff sleeves and tie waist detail. Worn once for an event.",
    category: 'DRESS',
    brand: 'REFORMATION',
    color: 'Red',
    size: 'S',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 78,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-w1',
        imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-1', name: 'Claire Dupont', city: 'New York', state: 'NY' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'women-2',
    title: "Women's Cropped Cable-Knit Wool Sweater",
    description: "Warm cream women's knit with ribbed cuffs and round neck. Perfect layer for autumn.",
    category: 'TOPWEAR',
    brand: 'ZARA',
    color: 'Cream',
    size: 'M',
    condition: 'GOOD',
    estimatedSwapValue: 36,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-w2',
        imageUrl: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-2', name: 'Maya Lin', city: 'San Francisco', state: 'CA' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },

  // ── 2. Men ───────────────────────────────────────────────────────────────
  {
    id: 'men-1',
    title: "Men's Distressed Vintage Leather Biker Jacket",
    description: "Premium men's vintage brown lambskin biker jacket with heavy brass zippers and quilted satin lining.",
    category: 'OUTERWEAR',
    brand: 'SCHOTT NYC',
    color: 'Brown',
    size: 'L',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 180,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-m1',
        imageUrl: 'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-3', name: 'Marcus Vance', city: 'Austin', state: 'TX' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'men-2',
    title: "Men's Classic Oxford Tailored Shirt",
    description: "Crisp men's formal dress shirt in sky blue woven cotton with mother-of-pearl buttons.",
    category: 'TOPWEAR',
    brand: 'RALPH LAUREN',
    color: 'Sky Blue',
    size: 'M',
    condition: 'NEW',
    estimatedSwapValue: 65,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-m2',
        imageUrl: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-4', name: 'Julian Hayes', city: 'Seattle', state: 'WA' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },

  // ── 3. Kids ──────────────────────────────────────────────────────────────
  {
    id: 'kids-1',
    title: 'Kids Corduroy Overalls & Striped Tee Set',
    description: 'Adorable unisex kids vintage mustard corduroy overalls with snap buttons and matching tee.',
    category: 'BOTTOMWEAR',
    brand: 'MINI RODINI',
    color: 'Mustard',
    size: 'S',
    condition: 'NEW',
    estimatedSwapValue: 45,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-k1',
        imageUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-5', name: 'Sarah Jenkins', city: 'Denver', state: 'CO' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'kids-2',
    title: 'Kids Puffer Hooded Weatherproof Parka',
    description: 'Warm and durable kids winter puffer jacket with reflective safety accents and fleece lining.',
    category: 'OUTERWEAR',
    brand: 'PATAGONIA',
    color: 'Navy',
    size: 'M',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 68,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-k2',
        imageUrl: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-5', name: 'Sarah Jenkins', city: 'Denver', state: 'CO' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },

  // ── 4. Home ──────────────────────────────────────────────────────────────
  {
    id: 'home-1',
    title: 'Home Artisanal Handwoven Fringe Throw Blanket',
    description: 'Cozy home decor handwoven textured throw blanket in neutral cream and earthy tones.',
    category: 'ACCESSORIES',
    brand: 'WEST ELM',
    color: 'Cream',
    size: 'One Size',
    condition: 'NEW',
    estimatedSwapValue: 62,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-h1',
        imageUrl: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-6', name: 'Elena Rostova', city: 'Portland', state: 'OR' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'home-2',
    title: 'Home Minimalist Ceramic Vase & Dried Floral Decor',
    description: 'Modern organic ceramic vase for aesthetic home living room and bedroom styling.',
    category: 'ACCESSORIES',
    brand: 'CB2',
    color: 'Terracotta',
    size: 'One Size',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 48,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-h2',
        imageUrl: 'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-6', name: 'Elena Rostova', city: 'Portland', state: 'OR' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },

  // ── 5. Pets ──────────────────────────────────────────────────────────────
  {
    id: 'pets-1',
    title: 'Pets Chunky Cable-Knit Wool Dog Sweater',
    description: 'Cozy autumn pets dog sweater with ribbed collar and comfortable leg openings.',
    category: 'ACCESSORIES',
    brand: 'BARK & CO',
    color: 'Heather Grey',
    size: 'M',
    condition: 'NEW',
    estimatedSwapValue: 34,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-p1',
        imageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-7', name: 'Oliver Twist', city: 'Chicago', state: 'IL' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'pets-2',
    title: 'Pets High-Visibility Waterproof Dog Raincoat',
    description: 'Yellow waterproof pets jacket with reflective striping and breathable mesh inner lining.',
    category: 'ACCESSORIES',
    brand: 'RUFFWEAR',
    color: 'Yellow',
    size: 'L',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 42,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-p2',
        imageUrl: 'https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-7', name: 'Oliver Twist', city: 'Chicago', state: 'IL' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },

  // ── 6. Electronics ───────────────────────────────────────────────────────
  {
    id: 'elec-1',
    title: 'Electronics Heritage Italian Leather Smartwatch Strap',
    description: 'Handcrafted top-grain leather electronics band compatible with Apple Watch 40mm/44mm/Ultra.',
    category: 'ACCESSORIES',
    brand: 'NOMAD',
    color: 'Cognac',
    size: 'One Size',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 65,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-e1',
        imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-8', name: 'Daniel Chen', city: 'San Jose', state: 'CA' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'elec-2',
    title: 'Electronics Wireless Over-Ear Active Noise-Cancelling Headphones',
    description: 'Matte black premium electronics headphones with travel hard case and high-fidelity sound.',
    category: 'ACCESSORIES',
    brand: 'SONY',
    color: 'Black',
    size: 'One Size',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 195,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-e2',
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-8', name: 'Daniel Chen', city: 'San Jose', state: 'CA' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },

  // ── 7. Luxury ────────────────────────────────────────────────────────────
  {
    id: 'lux-1',
    title: 'Luxury Quilted Lambskin Flap Shoulder Bag',
    description: 'Timeless luxury double flap bag in black lambskin leather with 24k gold-plated CC turnlock.',
    category: 'ACCESSORIES',
    brand: 'CHANEL',
    color: 'Black',
    size: 'One Size',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 850,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-l1',
        imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-9', name: 'Victoria Sterling', city: 'Miami', state: 'FL' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'lux-2',
    title: 'Luxury Silk Jacquard Monogram Heritage Scarf',
    description: 'Iconic luxury Italian silk square scarf with hand-rolled borders in rich burgundy and cream.',
    category: 'ACCESSORIES',
    brand: 'GUCCI',
    color: 'Burgundy',
    size: 'One Size',
    condition: 'NEW',
    estimatedSwapValue: 320,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-l2',
        imageUrl: 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-9', name: 'Victoria Sterling', city: 'Miami', state: 'FL' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },

  // ── 8. Beauty ────────────────────────────────────────────────────────────
  {
    id: 'beauty-1',
    title: 'Beauty Quilted Velvet Cosmetics Vanity Case',
    description: 'Elegant beauty organizer in rose velvet with gold zipper and water-resistant interior lining.',
    category: 'ACCESSORIES',
    brand: 'DIOR',
    color: 'Rose',
    size: 'One Size',
    condition: 'NEW',
    estimatedSwapValue: 68,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-b1',
        imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-10', name: 'Camille Laurent', city: 'New York', state: 'NY' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'beauty-2',
    title: 'Beauty English Pear & Freesia Cologne Set',
    description: 'Sensuous beauty fragrance with notes of just-ripe pears and white freesias, with velvet pouch.',
    category: 'ACCESSORIES',
    brand: 'JO MALONE',
    color: 'Amber',
    size: 'One Size',
    condition: 'NEW',
    estimatedSwapValue: 92,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-b2',
        imageUrl: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-10', name: 'Camille Laurent', city: 'New York', state: 'NY' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },

  // ── 9. Plus (Size XL) ─────────────────────────────────────────────────────
  {
    id: 'plus-1',
    title: 'Plus Size Emerald Velvet Wrap Cocktail Dress',
    description: 'Flattering plus size deep green velvet wrap dress with tulip hem and waist-cinching tie.',
    category: 'DRESS',
    brand: 'TORRID',
    color: 'Emerald',
    size: 'XL',
    condition: 'NEW',
    estimatedSwapValue: 75,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-pl1',
        imageUrl: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-11', name: 'Rachel Adams', city: 'Dallas', state: 'TX' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'plus-2',
    title: 'Plus Size High-Waisted Stretch Wide Leg Trousers',
    description: 'Ultra-comfortable plus size pleated trousers in dark espresso with elasticized back waist.',
    category: 'BOTTOMWEAR',
    brand: 'UNIVERSAL STANDARD',
    color: 'Espresso',
    size: 'XL',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 62,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-pl2',
        imageUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-11', name: 'Rachel Adams', city: 'Dallas', state: 'TX' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },

  // ── 10. Petite (Size XS) ──────────────────────────────────────────────────
  {
    id: 'petite-1',
    title: 'Petite Tailored Houndstooth Structured Blazer',
    description: 'Proportion-perfect petite double-breasted wool blazer with notched lapels and horn buttons.',
    category: 'OUTERWEAR',
    brand: 'J.CREW PETITE',
    color: 'Black/White',
    size: 'XS',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 89,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-pt1',
        imageUrl: 'https://images.unsplash.com/photo-1554412933-514a83d2f3c8?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-12', name: 'Mei Ling', city: 'Boston', state: 'MA' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'petite-2',
    title: 'Petite Bias-Cut Pleated Satin Slip Skirt',
    description: 'Chic petite midi slip skirt in champagne satin with comfortable hidden elastic waistband.',
    category: 'BOTTOMWEAR',
    brand: 'ANTHROPOLOGIE',
    color: 'Champagne',
    size: 'XS',
    condition: 'NEW',
    estimatedSwapValue: 58,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-pt2',
        imageUrl: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-12', name: 'Mei Ling', city: 'Boston', state: 'MA' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },

  // ── 11. Trending ─────────────────────────────────────────────────────────
  {
    id: 'trend-1',
    title: 'Trending Streetwear Washed Heavyweight Boxy Hoodie',
    description: 'Trending oversized 450gsm loopback cotton hoodie with dropped shoulders and distressed vintage wash.',
    category: 'TOPWEAR',
    brand: 'FEAR OF GOD',
    color: 'Vintage Black',
    size: 'L',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 110,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-t1',
        imageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-13', name: 'Zane Malik', city: 'Atlanta', state: 'GA' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'trend-2',
    title: 'Trending Retro Chunky Platform Lug-Sole Loafers',
    description: 'Trending polished calfskin loafers with exaggerated lug sole and brushed silver buckle.',
    category: 'FOOTWEAR',
    brand: 'PRADA',
    color: 'Black',
    size: '38',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 240,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-t2',
        imageUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-13', name: 'Zane Malik', city: 'Atlanta', state: 'GA' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },

  // ── 12. Brand ────────────────────────────────────────────────────────────
  {
    id: 'brand-1',
    title: 'Brand Vintage 501 Original Selvedge Jeans',
    description: 'Iconic brand high-waisted wash straight leg denim with classic button fly and red-line selvedge.',
    category: 'BOTTOMWEAR',
    brand: "LEVI'S",
    color: 'Medium Blue',
    size: '32',
    condition: 'GOOD',
    estimatedSwapValue: 52,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-br1',
        imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-14', name: 'Lucas Scott', city: 'Nashville', state: 'TN' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'brand-2',
    title: 'Brand Double-Breasted Wool Blend Camel Trench Coat',
    description: 'Double-breasted trench in camel wool blend. Relaxed modern tailoring from flagship brand.',
    category: 'OUTERWEAR',
    brand: 'ARITZIA',
    color: 'Camel',
    size: 'M',
    condition: 'NEW',
    estimatedSwapValue: 120,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-br2',
        imageUrl: 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-14', name: 'Lucas Scott', city: 'Nashville', state: 'TN' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'kids-showcase-1',
    title: 'Kids Cozy Sherpa Fleece Zip Jacket',
    description: 'Ultra-soft recycled fleece jacket for kids with zip pockets and windproof collar.',
    category: 'OUTERWEAR',
    brand: 'PATAGONIA',
    color: 'Navy',
    size: 'M (Kids)',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 55,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-ks1',
        imageUrl: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-15', name: 'Sarah Miller', city: 'Denver', state: 'CO' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'kids-showcase-2',
    title: 'Girls Pastel Floral Cotton Tiered Dress',
    description: 'Charming girls tiered sundress with flutter sleeves and lightweight breathable organic cotton.',
    category: 'DRESS',
    brand: 'ZARA KIDS',
    color: 'Pastel Floral',
    size: 'S (Girls)',
    condition: 'NEW',
    estimatedSwapValue: 38,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-ks2',
        imageUrl: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-16', name: 'Emily Clark', city: 'Austin', state: 'TX' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'men-showcase-1',
    title: "Men's Heavyweight Flannel Plaid Workshirt",
    description: "Thick brushed cotton men's button-up shirt in classic red and black buffalo check.",
    category: 'TOPWEAR',
    brand: 'RALPH LAUREN',
    color: 'Red/Black Plaid',
    size: 'L',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 60,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-ms1',
        imageUrl: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-17', name: 'David Evans', city: 'Portland', state: 'OR' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
  {
    id: 'men-showcase-2',
    title: "Men's Italian Wool Tailored Modern Blazer",
    description: "Sophisticated men's dark navy two-button tailored blazer crafted from fine Italian wool.",
    category: 'OUTERWEAR',
    brand: 'J.CREW',
    color: 'Navy',
    size: '40R',
    condition: 'LIKE_NEW',
    estimatedSwapValue: 140,
    status: 'AVAILABLE',
    images: [
      {
        id: 'img-ms2',
        imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
        createdAt: '2026-10-01',
      },
    ],
    owner: { id: 'o-18', name: 'Marcus Vance', city: 'Chicago', state: 'IL' },
    createdAt: '2026-10-01',
    updatedAt: '2026-10-01',
  },
];
